version: '3'

services:
  database:
    build:
      context: contrib/mysql
      dockerfile: Dockerfile
    ports:
      - "33063:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8991:80"
    environment:
      PMA_HOST: database
