<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJKxRtat\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJKxRtat/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJKxRtat.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJKxRtat\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJKxRtat\App_KernelDevDebugContainer([
    'container.build_hash' => 'JKxRtat',
    'container.build_id' => '6972b7b1',
    'container.build_time' => 1663729116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJKxRtat');
